# configuration for https://github.com/EmbarkStudios/cargo-deny

[advisories]
yanked = "deny"

[bans]
multiple-versions = "allow"

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "0BSD",
    "Zlib",
    "Unicode-3.0",
    "Unlicense",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
